export const EGYPT_STATES = [
  { code: "EGC", nameEn: "Cairo", nameAr: "القاهرة" },
  { code: "EGGZ", nameEn: "Giza", nameAr: "الجيزة" },
  { code: "EGALX", nameEn: "Alexandria", nameAr: "الإسكندرية" },
  { code: "EGKB", nameEn: "Qalyubia", nameAr: "القليوبية" },
  { code: "EGSHR", nameEn: "Sharqia", nameAr: "الشرقية" },
  { code: "EGDK", nameEn: "Dakahlia", nameAr: "الدقهلية" },
  { code: "EGBH", nameEn: "Beheira", nameAr: "البحيرة" },
  { code: "EGGH", nameEn: "Gharbia", nameAr: "الغربية" },
  { code: "EGMNF", nameEn: "Monufia", nameAr: "المنوفية" },
  { code: "EGKFS", nameEn: "Kafr El Sheikh", nameAr: "كفر الشيخ" },
  { code: "EGDT", nameEn: "Damietta", nameAr: "دمياط" },
  { code: "EGPTS", nameEn: "Port Said", nameAr: "بورسعيد" },
  { code: "EGIS", nameEn: "Ismailia", nameAr: "الإسماعيلية" },
  { code: "EGSUZ", nameEn: "Suez", nameAr: "السويس" },
  { code: "EGBA", nameEn: "Red Sea", nameAr: "البحر الأحمر" },
  { code: "EGWAD", nameEn: "New Valley", nameAr: "الوادي الجديد" },
  { code: "EGMT", nameEn: "Matrouh", nameAr: "مطروح" },
  { code: "EGKN", nameEn: "Qena", nameAr: "قنا" },
  { code: "EGAST", nameEn: "Asyut", nameAr: "أسيوط" },
  { code: "EGSHG", nameEn: "Sohag", nameAr: "سوهاج" },
  { code: "EGASN", nameEn: "Aswan", nameAr: "أسوان" },
  { code: "EGLX", nameEn: "Luxor", nameAr: "الأقصر" },
  { code: "EGBNS", nameEn: "Beni Suef", nameAr: "بني سويف" },
  { code: "EGFYM", nameEn: "Faiyum", nameAr: "الفيوم" },
  { code: "EGMN", nameEn: "Minya", nameAr: "المنيا" },
  { code: "EGJS", nameEn: "South Sinai", nameAr: "جنوب سيناء" },
  { code: "EGSIN", nameEn: "North Sinai", nameAr: "شمال سيناء" },
] as const;
